### ISSUE TITLE
[Bug] - esx_identity - UI doesn't show.

### ISSUE THREAD

**Issue by xj0le** [esx-framework/esx-legacy#679]
UI for register basically doesn't show, I have every dependency needed for esx_identity. No errors or whatsoever.
![218_20220926012947_1](https://user-images.githubusercontent.com/55405106/201551522-c1a3bf26-dee6-4683-aa49-01aebf7339fc.png)

**Comment by Moslowww** [comment]
This is good for me

**Comment by HirboSH** [comment]
Hey! Did you check for any errors in DevTools? If not and the bug is still occurring it'll help me! Thanks! 

(F8 > Tools > NUI > Open DevTools > hover to console tab and see if there's any errors related to the resource)

**Comment by HirboSH** [comment]
Hey! Problem got fixed at the last push!

**Comment by CsokiHUN** [comment]
I think its fixed in #688 and #702

**Comment by Gellipapa** [comment]
Hi! It has been fixed please update your esx_identity and retest.  Please report back thank you. @xj0le

**Comment by xj0le** [comment]
Still doesn't work for me, I updated it to the newest...

No errors or whatsoever, only from ox_inventory.

![image](https://user-images.githubusercontent.com/55405106/205113326-babbd933-05fb-4321-a60d-0630b3a5dd1f.png)

**Comment by Gellipapa** [comment]
@xj0le Hi! Update latest version, do not just copy the esx_identity but update the whole esx legacy.

**Comment by CsokiHUN** [comment]
es_extended must be the latest, downloaded from the source and not from the release!

**Comment by xj0le** [comment]
> es_extended must be the latest, downloaded from the source and not from the release!

Exactly what I did.

**Comment by Tinky124** [comment]
We still have problem..

**Comment by Mattt2283** [comment]
No issue for me
